[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  port = 8888
  targetPort = 3000
  command = "npm run dev"

# Environment variables can be set in Netlify UI
# or in a .env file locally (not committed to git)